region           = "europe-west1"
zone             = "europe-west1-b"
jenkins_name     = "jenkins-server"
network_name     = "petclinic-vpc-tf"
subnetwork_name  = "petclinic-subnet-tf-eu-west1"
cluster_name     = "petclinic-cluster"
pod_range        = "k8s-pod-range"
service_range    = "k8s-service-range"